### ISSUE TITLE
[Bug]: Stuck in Paintball arena / Can join unauthed radio channels

### ISSUE THREAD

**Issue by Soxxxyy** [fayynt/issues#10]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

Played in a five lives paintballing session today with the Aztecas et al. I was the last alive with lives. Stuck in paintball arena for half an hour due to Government being busy with their RP. Whilst stuck the radio channel changed to PD radio and I could speak in it (literally not on radio, then boom was on radio channel for PD). Larry & Jeevz tried to TP me out of the arena, but couldnt as they kept falling through the map. Eventually Jeevz had to kill me several times to lose the lives, which then allowed him to TP me out. 

Likely a script issue?

### Expected behaviour

Not for that to occur. 

### Steps to reproduce

As above. 

### Discord ID

Soxxxyy

**Comment by fayynt** [comment]
Please reiterate paintball issue.

Joining unauthed channels fixed.
