### ISSUE TITLE
[Bug]: oil rig job

### ISSUE THREAD

**Issue by B033y21** [fayynt/issues#100]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

Done the oil rig 3 times and everytime I have been kicked, I get the 3rd crate off the boat about to exit the crane and then it just kicks me from server, I’ve done it 3 times and each time I get kicked meaning I ain’t earning anything and then I have to wait over an hour just to retry  

### Expected behaviour

To be able to finish the job and get paid 

### Steps to reproduce

Help

### Discord ID

cbfs101

**Comment by FellaHighOnaBoat** [comment]
Old V1 bug
