### ISSUE TITLE
[Bug]: Driving test and theory tests incorrect

### ISSUE THREAD

**Issue by AaronSadlerUK** [fayynt/issues#102]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

The prices listed in the description for the driving test and theory test are lower than the actual prices

### Expected behaviour

The prices to be accurate

### Steps to reproduce

Read the driving test description
Purchase a driving test

### Discord ID

480343515935801365

**Comment by FellaHighOnaBoat** [comment]
should match in V2
