### ISSUE TITLE
[Bug]: PD Armoury 

### ISSUE THREAD

**Issue by TheOGYonder** [fayynt/issues#103]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

DAC, commander & Detective superintendant can;t access armoury 

### Expected behaviour

All ranks to be able to access Armoury 

### Steps to reproduce

1. Set Police job 
2. go to armoury and Press "E" To open door 

### Discord ID

TheOGYonder#7910

**Comment by fayynt** [comment]
fixed
