### ISSUE TITLE
[Bug]: Dosen't Give us keys to our PD cars

### ISSUE THREAD

**Issue by martine567** [fayynt/issues#105]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

When we requested to get our cars given to us by Daniel Degrassi, we tried to take them out of the garage and when we did we had to hot wire the cars, so we were not given our keys. I am not sure if this is only a PD car issue though.

### Expected behaviour

Us to be given the keys? idk what to write for that.

### Steps to reproduce
to sort it out you need to hot wire it then put it away
### Discord ID

tapoutboy

**Comment by fayynt** [comment]
After the changes that were made today/yesterday, is this still happening?

**Comment by FellaHighOnaBoat** [comment]
stale
