### ISSUE TITLE
[Bug]: Lumberjack breaks when using controller.

### ISSUE THREAD

**Issue by steblood** [fayynt/issues#106]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

Lumberjack job is bugging out, people are activating the crane 'controller' however the crane controller script is not cancelling out the movement as it should normally.
https://medal.tv/games/gta-v/clips/2aJuyANkmk3rIF/d1337wcz8L76?invite=cr-MSxPYkMsMjAwOTkyODQ3LA

### Expected behaviour

Controller should control the crane and disable movement functions

### Steps to reproduce

No steps, very random

### Discord ID

137269875008733185

**Comment by FellaHighOnaBoat** [comment]
stale
