### ISSUE TITLE
[Bug]: 2 locations on map that break GPS

### ISSUE THREAD

**Issue by steblood** [fayynt/issues#107]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

Driving through these two locations with GPS activated, cancels out the GPS and you lose the marker.

Approx. location; 752 % 725
https://media.discordapp.net/attachments/1056697085321285693/1231990341834506433/image.png?ex=66345a2a&is=663308aa&hm=fd523ad97f89971cbd11b50c28dcd918f9e69bb5bd884d77dc21cf2e9f51d23f&=&format=webp&quality=lossless

https://media.discordapp.net/attachments/1235283292161314927/1235529172189974528/image.png?ex=6634b3b5&is=66336235&hm=669a80530a2b0f91c7ead9a76c438446349305a70cfd13e8d9cfc9ba0fed8dec&=&format=webp&quality=lossless&width=550&height=286

### Expected behaviour

GPS to continue as normal

### Steps to reproduce

Go to location and drive through with GPS activated.

### Discord ID

137269875008733185

**Comment by FellaHighOnaBoat** [comment]
Cannot fix
