### ISSUE TITLE
[Bug]: Dealer - Red Skull and cross bones

### ISSUE THREAD

**Issue by steblood** [fayynt/issues#108]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

Dealer - Red Skull and cross bones
Wholesaler doesn't give you gps or anything
Retailer works fine

### Expected behaviour

To issue correct items

### Steps to reproduce

Visit dealer and try to receive items

### Discord ID

137269875008733185

**Comment by FellaHighOnaBoat** [comment]
Is this still happening?

**Comment by fayynt** [comment]
what
