### ISSUE TITLE
[Bug]: Fuel station import / export deliveries

### ISSUE THREAD

**Issue by steblood** [fayynt/issues#109]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

When trying to import and export your own fuel for a fuel station, upon starting the job, the tractor until is spawning but the tanker is not.

### Expected behaviour

Tanker to spawn with tractor unit

### Steps to reproduce

Start a import/export job at a fuel station

### Discord ID

137269875008733185

**Comment by FellaHighOnaBoat** [comment]
is this still happening

**Comment by fayynt** [comment]
response plz
