### ISSUE TITLE
[Bug]: Shop 'stock' jobs not working correctly

### ISSUE THREAD

**Issue by steblood** [fayynt/issues#110]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

When starting a job for an in city shop, the job starts, many people have been experiencing issues with actually seeing the packages they're trying to collect. Not allowing them to collect and complete the job.

Some others have collected packages and then the packages have disappeared.

### Expected behaviour

Packages to be visable or working in order to complete the job.

### Steps to reproduce

Start a shop 'stock' job.

### Discord ID

137269875008733185

**Comment by FellaHighOnaBoat** [comment]
Is this still happening?

**Comment by fayynt** [comment]
sdsda
