### ISSUE TITLE
[Bug]: House robberies are under water

### ISSUE THREAD

**Issue by steblood** [fayynt/issues#111]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

When entering a house robbery, the inside of the house is full of water, so you are swimming under water to complete the robbery

https://cdn.discordapp.com/attachments/1235283292161314927/1235361639717670912/Moments-Desktop-clip-from-May-01-2024.mp4?ex=663417ae&is=6632c62e&hm=bf5e5bd9efe26635151a52c1422b80f28f2b25d6bb6ede8de6d8701fac5902a3&

Video for context

### Expected behaviour

House not to be full of water

### Steps to reproduce

Enter a house robbery.

### Discord ID

137269875008733185

**Comment by FellaHighOnaBoat** [comment]
Discord is not a valid CDN. Please upload new proof or close this issue
