### ISSUE TITLE
[Bug]: Garage issues (after old garage system added)

### ISSUE THREAD

**Issue by steblood** [fayynt/issues#112]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

When pulling out some cars they are duplicating;
Some people are unable to access their garage.
Some people's cars will not spawn at all.
Some dealership cars are disappearing from people's garages
Some people cannot even see the prompt to access the garage

### Expected behaviour

For garages to work.

### Steps to reproduce

It seems to be different for everybody.

### Discord ID

137269875008733185

**Comment by fayynt** [comment]
Still happening?

**Comment by FellaHighOnaBoat** [comment]
stale
