### ISSUE TITLE
[Bug]: Contruction job causes black screen / crash

### ISSUE THREAD

**Issue by steblood** [fayynt/issues#113]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

When trying to start a job at contruction, after pressing 'start job', the screen goes black leaving you unable to do anything apart from quit the game. Video for reference.

https://medal.tv/games/gta-v/clips/2aKg37ZVDhuNia/d1337KwMgM3J?invite=cr-MSxQemIsNTI3NDcwODQs

### Expected behaviour

Contruction job should start.

### Steps to reproduce

Follow video provided.

### Discord ID

137269875008733185

**Comment by fayynt** [comment]
still happening?

**Comment by steblood** [comment]
Fixed - Nice work mate
