### ISSUE TITLE
[Bug]: delivering and selling drugs

### ISSUE THREAD

**Issue by steblood** [fayynt/issues#115]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

Prompt to press E to deliver/sell drugs keeps flashing upon a certain delivery point

https://medal.tv/games/gta-v/clips/2aLf8TmHGkhL1E/d1337ZXrSdxh?invite=cr-MSw1bVQsMTgzMTIzNzY5LA

it has been noted that spamming the guy works.

### Expected behaviour

Should just deliver/sell

### Steps to reproduce

Try to sell or deliver drugs

### Discord ID

137269875008733185

**Comment by FellaHighOnaBoat** [comment]
@steblood is this still happening?

**Comment by fayynt** [comment]
closed due to no reponse!!!!!
