### ISSUE TITLE
[Bug]: London Logistics Truck Fuel

### ISSUE THREAD

**Issue by steblood** [fayynt/issues#117]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

LL Trucks are using a lot of fuel very fast.
The image below is a representation of a 2.31 mile journey there and back.
We wouldn't be able to manage the longer journeys.

https://media.discordapp.net/attachments/1175734364429103135/1235747558740066404/image.png?ex=66357f19&is=66342d99&hm=d143d02700cfa605a61811e761c7d222f5a738b0f24e3c62c9251b6988d4530a&=&format=webp&quality=lossless&width=1144&height=671

### Expected behaviour

Full tank of fuel to cover 40 miles total

### Steps to reproduce

Complete any LL job.

### Discord ID

137269875008733185

**Comment by FellaHighOnaBoat** [comment]
Discord is not a valid CDN. 

Please review this and either update the proof or if its fixed please advise

**Comment by FellaHighOnaBoat** [comment]
stale
