### ISSUE TITLE
[Bug]: civis on yacht heist cannot be looted

### ISSUE THREAD

**Issue by xksiitz** [fayynt/issues#12]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

unable too loot bodies on the yacht heist

### Expected behaviour

too be able too loot them for there guns etc

### Steps to reproduce

add the ability to do so

### Discord ID

xskiitz

**Comment by fayynt** [comment]
You are not meant to loot the NPC's. They are there to counter you trying to steal the items in the yacht.
