### ISSUE TITLE
[Bug]: Unlocking/Locking Car

### ISSUE THREAD

**Issue by Abid-M** [fayynt/issues#120]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

Bug Report: Unlocking/locking car bit buggy where its unlocked but when clicking u says unlocked when already unlocked and vice versa. Couple times needed to click u in order to lock/unlock

### Expected behaviour

Self-explanatory

### Steps to reproduce

Press u

### Discord ID

240809008938745856

**Comment by FellaHighOnaBoat** [comment]
fixed
