### ISSUE TITLE
[Bug]: banks 

### ISSUE THREAD

**Issue by Mason5479** [fayynt/issues#122]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

When trying to start a bank robbery it bugs out and doesn’t work 

### Expected behaviour

For the bank robbery to work and not bug out 

### Steps to reproduce

 Fix banks 

### Discord ID

811267255664771122

**Comment by MarcosLDNRP** [comment]
Is there an existing issue for this?
 I have searched for existing issues but there are none
Description
When in Jail I cannot get out of cuffs and I am not able to move 

Expected behaviour
Be uncuffed when I arrive in Jail

Steps to reproduce
Take me out of cuffs

Discord ID
968458483907313704

**Comment by FellaHighOnaBoat** [comment]
Blame PD for sending you up in cuffs
