### ISSUE TITLE
[Bug]: Shop jobs - Not working correctly

### ISSUE THREAD

**Issue by steblood** [fayynt/issues#124]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

When collecting stock for in city shops, the stock (boxes) are not spawning in at the location the tracker takes them too.

In the below images, you can see the blip on the map is showing them to go to location to collect, however the stock is not there to be collected.

![image](https://github.com/fayynt/issues/assets/107085449/caf4b748-1d6e-47bf-a51c-11ed122262bc)
![image](https://github.com/fayynt/issues/assets/107085449/9ca230aa-cbdb-4991-ae75-a43a19f367c4)

### Expected behaviour

Items to be visible when arriving at collection location.

### Steps to reproduce

Start a job at any in city shop

### Discord ID

137269875008733185

**Comment by FellaHighOnaBoat** [comment]
stale
