### ISSUE TITLE
[Bug]: at all fleecas when we try to start it doesnt work

### ISSUE THREAD

**Issue by Cgore639** [fayynt/issues#125]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

when i press e to start heist the heist doesnt start and i tried to shoot  a bullet to activate it and it didnt work, i also had all the requirements.

### Expected behaviour

to fix it please

### Steps to reproduce

![Uploading Screenshot 2024-05-09 160759.png…]()

### Discord ID

cgore639

**Comment by FellaHighOnaBoat** [comment]
Did you have the required item to start the heist? (Purposely not disclosing it - find out the item in RP)
