### ISSUE TITLE
[Bug]: cant get back in game after lockpicking door, keeps crashing

### ISSUE THREAD

**Issue by BernieMacHub** [fayynt/issues#127]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

Lockpicked a house, game crashed immediately after, now when i load back up, it crashes everytime i select my character

### Expected behaviour

i expect i should be inside the house

### Steps to reproduce

start the game.

### Discord ID

506205293181403137

**Comment by FellaHighOnaBoat** [comment]
Do you have a clip of this?

**Comment by fayynt** [comment]
Closed due to no response + most likely fixed.
