### ISSUE TITLE
[Bug]: Amulance System: Some people don't die when stabbed.

### ISSUE THREAD

**Issue by steblood** [fayynt/issues#128]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

When somebody is stabbed/hit with something or shot. They're knocked out instead of being put into phase 1 death.
When knocked out, the person who is knocked out takes zero damage allowing them to get up and instantly take the upper hand as people aren't generally ready for it, nor should they be because they've stabbed the knocked out person more than enough times on the floor for them to be stage 2.

### Expected behaviour

People enter phase 1 quicker. Damage to be dealt when knocked out and lying on the floor, regardless of weapon.

### Steps to reproduce

Shoot/stab/hit somebody until they're knocked out.

### Proof

https://medal.tv/games/gta-v/clips/2f6tSKbo8afcd7/d1337QKKXXte?invite=cr-MSxvclEsMjExMTYwOTgyLA

### Discord ID

137269875008733185

**Comment by fayynt** [comment]
Should be fixed... please reopen if it isnt
