### ISSUE TITLE
[Bug]: Bandages dont remove after use

### ISSUE THREAD

**Issue by RG2Kelvin** [fayynt/issues#129]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

Bandages dont remove after use

### Expected behaviour

loss them after use

### Steps to reproduce

use it 

### Proof

.

### Discord ID

575632373077770260

**Comment by fayynt** [comment]
what bandage

**Comment by fayynt** [comment]
Still happening?

**Comment by RG2Kelvin** [comment]
Nope found the issue, bandages spawning in gloveboxes with wrong spawncode
