### ISSUE TITLE
[Bug]: When staffing on armour is lost

### ISSUE THREAD

**Issue by steblood** [fayynt/issues#130]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

When staffinf on armour is lost, regardless of how it was given.

### Expected behaviour

Armour to stay on person who staffed on/off

### Steps to reproduce

Put armour on and staff on.

### Proof

https://medal.tv/games/gta-v/clips/2fujmvv7fqnr-4/d1337ETLzsE4?invite=cr-MSxZWkMsNzExOTM5OTEs

### Discord ID

137269875008733185

**Comment by fayynt** [comment]
Fixed (after restart)
