### ISSUE TITLE
[Bug]: Construction Job 

### ISSUE THREAD

**Issue by TheOGYonder** [fayynt/issues#131]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

Construction job Seems to be having a few issues just now. 
Main issues appear to be Completing all the tasks And the progress bar not showing 100% and no icons on the map to Show anymore to be done.
Not Being able to end the job Before 100% If not wanting to do full job 
Issue with one of the sites down at the beach (Postal Code 696) Where the job goes to 98.5 % However Job is completed 

### Expected behaviour

Job progress to show 100% When all tasks completed
Be able to end job before 100% 

### Steps to reproduce

Get construction job
Start Job
Repeat this to see issues that arise 

### Proof

https://www.youtube.com/watch?v=SSP3WCiQyX8

### Discord ID

TheOGYonder#7910

**Comment by fayynt** [comment]
probably an invisible task, can soemone check 😭😭 @FellaHighOnaBoat
