### ISSUE TITLE
[Bug]: postal code 510 - bug

### ISSUE THREAD

**Issue by emz8715** [fayynt/issues#132]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

We were made aware of a bug , postal code 510 i failed the lock pick but was still able to get in the house after.

### Expected behaviour

I would assume it shouldn’t let you in

### Steps to reproduce

Go to the house and third eye it

### Proof

https://medal.tv/games/gta-v/clips/2fSs5vTqgSEmBD/d1337ir5vIN2?invite=cr-MSxNY3osMjMyNTM5ODUxLA

### Discord ID

1114635293631463434

**Comment by FellaHighOnaBoat** [comment]
stale
