### ISSUE TITLE
[Bug]: Not being able to see the full vipmenu 

### ISSUE THREAD

**Issue by oldhamste** [fayynt/issues#133]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

Report via modmail 

### Expected behaviour

/vipshop 

### Steps to reproduce

change resolution, screen and display settings  

### Proof

![Capture_12](https://github.com/fayynt/issues/assets/50807817/325ab1dd-4255-4906-a124-22be3dc178f5)

### Discord ID

1192446263564701866

**Comment by FellaHighOnaBoat** [comment]
@oldhamste what resolution are you using for fivem?

**Comment by oldhamste** [comment]
1080 x 1920 pal
