### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Bobby132123** [fayynt/issues#134]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

in the recycling bit the red arrow you should get some times disappears and then you cant get out and cant get off duty.

### Expected behaviour

the red arrow shouldnt go away

### Steps to reproduce

not to sure

### Proof

![fivem](https://github.com/fayynt/issues/assets/171394267/6c0b8466-f96d-4bea-8ed1-b0b90f56cb29)

### Discord ID

1245414808975573085

**Comment by FellaHighOnaBoat** [comment]
cant repro
