### ISSUE TITLE
[Bug]: EMS Menu not working

### ISSUE THREAD

**Issue by Dragoniul** [fayynt/issues#137]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

sometime when clocked into nhs you cant access the F1 Menu untill you clock out 

### Expected behaviour

to have access when clocked in NHS

### Steps to reproduce

Somtimes it work sometimes it doesnt 

### Proof

https://cdn.discordapp.com/attachments/1030962582825209888/1247195126036697168/image.png?ex=667047f9&is=666ef679&hm=0eff244df41cbb8e1e91667947d1ea85a01500ddfeec0cac39f2ca11408a93eb&

### Discord ID

Dragoniul

**Comment by fayynt** [comment]
No video, closed.
