### ISSUE TITLE
Hud bug 

### ISSUE THREAD

**Issue by F1Elliss** [fayynt/issues#140]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

The Hud options arnt saving once u apply them 

I put mini map on foot on i get in a car and get out and it takes it straight back off, and same with the speedometer it keeps going away and u have to go /hud then editor mode and drag it back into frame 

Also there isnt a notification saying your seatbelt isnt on or off

### Expected behaviour

Options save once u apply them, seatbelt has a notification once applied or taken off, and the speedo to stay once saved and not have to drag it back to frame 

### Steps to reproduce

not a clue 

### Proof

https://medal.tv/games/gta-v/clips/ihu2mfYJRN6tf8Y4h/d1337Gr01mkP?invite=cr-MSxPTWEsNzExOTM5OTEs

### Discord ID

722399446620700704

**Comment by fayynt** [comment]
Fixed minimap not staying in place, fixed seatbelt picture.

**Comment by F1Elliss** [comment]
there is also a black outline around the map and its not centerd is it possible to make it so u can remove that outline
