### ISSUE TITLE
[Bug]: Atm robbery

### ISSUE THREAD

**Issue by Andrewbait1** [fayynt/issues#142]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

I am trying to rob an atm but after attaching the rope and i try to drive off nothing happens. after attaching the rope to the atm it pops out the wall.

### Expected behaviour

Pretty sure its supposed to come off the wall with the rope

### Steps to reproduce

1. Use the rope on the car
2. use the rope on the atm
3. get in the car and drive

### Proof

https://medal.tv/games/gta-v/clips/iijNtZOZ0sdEMApsN/d1337qBa2yRV?invite=cr-MSxtOVIsMTgxMTAwODg5LA

### Discord ID

lilyachty

**Comment by fayynt** [comment]
To be honest, these atms robberies are horrendous. They will most likely be removed and replaced with a different easy to do robbery.
