### ISSUE TITLE
New Hud

### ISSUE THREAD

**Issue by F1Elliss** [fayynt/issues#144]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

U edit ur hud with /hud and once u get in a car it all unsaves and when u get back out its back to normal but while in the car its default and u cant edit the hud for when ur in the car 

Also cruise control doesnt work, u press the Key to do so it says turned on but it doesnt keep at that speed and excelarate for u insteadi locks u from going above the speed u pressed it at, meaning i press the key at 80mph the car doesnt excelarate  it slows down u go to excelarate and it wont let u go above 80mph till u turn it off 

### Expected behaviour

For the changes to be saved and be the same on foot and in the car

cruise control to excelarate for u 

### Steps to reproduce

no clue

### Proof

https://medal.tv/games/gta-v/clips/il8mGtvBEDNmyCvZQ/d1337GUM6fM9?invite=cr-MSxIWTIsNzExOTM5OTEs

https://medal.tv/games/gta-v/clips/il8ss85FC5ioLVJf3/d1337tZVk776?invite=cr-MSxxMTMsNzExOTM5OTEs

### Discord ID

722399446620700704

**Comment by fayynt** [comment]
isnt there a button to enable vehicle hud? or 
![image](https://github.com/user-attachments/assets/c166cbba-7844-486a-b200-7837565a3395)

**Comment by F1Elliss** [comment]
![image](https://github.com/user-attachments/assets/7b3abe82-d71e-4c73-8383-68df51d1c6c0)
nope

**Comment by fayynt** [comment]
![image](https://github.com/user-attachments/assets/46826b77-57fb-4291-adc2-9fcc38ec7f0e)

**Comment by F1Elliss** [comment]
ahh im blind as a cunt then either way cruise control is a no work

**Comment by fayynt** [comment]
im pretty sure its the intended way to work

**Comment by F1Elliss** [comment]
cruise control meant to drive for u and lock u at that speed, this one u still have to drive and and it only locks ur speed

**Comment by F1Elliss** [comment]
![image](https://github.com/user-attachments/assets/2dc371d8-4fb5-4f0a-9903-c577b43b2687)
also this doesnt work when u pull a gun out it doesnt actually show that u have a gun and how many bullets u got left in the mag 

https://medal.tv/games/gta-v/clips/il98IESqUtCFQWTbC/d1337brhfhmy?invite=cr-MSxNQzgsNzExOTM5OTEs
