### ISSUE TITLE
[Bug]: Dealership showroom

### ISSUE THREAD

**Issue by beamishgoose** [fayynt/issues#147]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

Cars in the dealership show rooms are not loading in before people buy them

### Expected behaviour

So people can see the cars first

### Steps to reproduce

look in the showroom menu

### Proof

![Screenshot 2024-08-21 001132](https://github.com/user-attachments/assets/684221a9-c374-493d-8937-b7fe8085670a)

### Discord ID

692884269206339645

**Comment by fayynt** [comment]
client issue im pretty sure, cant replicate...
