### ISSUE TITLE
[Bug]: Spike Strips do not work around Legion, Evo, Red garage, Union, Vanilla Unicorn and other places

### ISSUE THREAD

**Issue by VoidSamael** [fayynt/issues#148]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

Everytime in a chase we put spike strips down, everytime we attempt spike strips in the city we place them and for the person who places them they are visible and work. but everyone else cannot see it and it does not take out their tires when they drive over it. Im unsure what it is but outside of the city and various low population areas spike strips work but in the high pop areas they fail to work.

### Expected behaviour

should be seen and take out tires anywhere in the city. instead of certain places

### Steps to reproduce

You need 2 people

Attempt 1:
1. Go to legion, Evo Etc
2. place spike strips.
3. the person who placed them will see them
4. the person who did not place them will be unable to see them and take no effect

Attempt 2:
1. Go to the highway near casino or the border, even sandy and paleto
2. place spikes
3. the person who placed them will see them
4. the person who did not place them will be able to see them and take effect

### Proof

There is no F8 errors and its very difficult to get a clip due to needing 2 different perspectives from 2 different people

### Discord ID

343372144329359371

**Comment by fayynt** [comment]
spike strips updated, recreate report if continues
