### ISSUE TITLE
[Bug]: PD lockboxes dont workl

### ISSUE THREAD

**Issue by AskJeevz** [fayynt/issues#149]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

dont show up on radial menu, checked all cars in script none of em show up ( i aint touched it)

### Expected behaviour

should be able to put guns in glovey innit

### Steps to reproduce

try it

### Proof

no proof s

### Discord ID

258320294018678784

**Comment by fayynt** [comment]
fixed
