### ISSUE TITLE
[Bug]: Possible YATCH ROBBERY to check if possible 

### ISSUE THREAD

**Issue by BIGJLUK** [fayynt/issues#15]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

Someone has claimed that when doing the yatch robbery after completing it and taking the items from the trays nothing gets put inside of their inventory.

### Expected behaviour

Receive the items expected from robbery 

### Steps to reproduce

N/A

### Discord ID

jxxk.lew

**Comment by fayynt** [comment]
Unable to reproduce, works for me.
