### ISSUE TITLE
[Bug]: /Wardrobe doesnt work

### ISSUE THREAD

**Issue by AskJeevz** [fayynt/issues#16]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

/wardrobe does not work for PD. when you clock in and do /wardrobe it doesnt work no wardrobe menu

### Expected behaviour

for /wardobe to work

### Steps to reproduce

Clock into PD
do /wardrobe
Profit

### Discord ID

Jeevz#0

**Comment by FellaHighOnaBoat** [comment]
Fixed
