### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by AskJeevz** [fayynt/issues#17]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

In the mechanics script, the licence plate number 5 or 6 used to completely black out a plate. Now it shows some north yankton plate. if possible, be nice to have the blacking out of plates back 

### Expected behaviour

the 5th 6th option to be blacking out the plate instead of yankton plate

### Steps to reproduce

Go to mechanics script
choose 5th to 6th option
profit

### Discord ID

Jeevz#0

**Comment by FellaHighOnaBoat** [comment]
Not entirely sure what you mean. All our plates are GTA standard and always have been.

**Comment by AskJeevz** [comment]
This was part of the tuning script which has since been removed. Can be closed thank you
