### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Lewis192411** [fayynt/issues#18]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

Using your PD radial menu to panic does not 100% work. Sometimes it does not work and even doing /panic does no work

### Expected behaviour

For panic buttons to work again

### Steps to reproduce

Clock onto PD
Open radial menu
Clip panic button

### Discord ID

695544491679154268

**Comment by fayynt** [comment]
Fixed
