### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Lewis192411** [fayynt/issues#19]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

Shots fired calls do not work anymore. When someone shoots an unsupressed weapon PD no longer get the dispatch calls for them

### Expected behaviour

When someone shoots an unsupressed weapon PD should get a dispatch call and a marker on their maps

### Steps to reproduce

Shoot a weapon that is not supressed
Have a PD check for shots fired

### Discord ID

695544491679154268

**Comment by fayynt** [comment]
Should be fixed, please check
