### ISSUE TITLE
[Bug]: Prison Garage will TP you through map when the vehicle spawns

### ISSUE THREAD

**Issue by AskJeevz** [fayynt/issues#22]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

When you select a vehicle from the garage at prison you will be TPD under the map with the vehicle then be teleported back to the top

### Expected behaviour

for you to not fall though the map

### Steps to reproduce

go to prison garage
choose a car
profit

### Discord ID

Jeevz#0

**Comment by fayynt** [comment]
Fixed
