### ISSUE TITLE
[Bug]: Women at paintball

### ISSUE THREAD

**Issue by LarryDinglebop** [fayynt/issues#23]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

Anytime you go to paintball as a woman if you pick blue team you have a constant black screen until killed for the first time but when your killed you die and don't re spawn like normal paintball you die and go to the crawling stage until you bleed out. You also spawn in with full red clothing while being on blue team. When you pick red team you have no torso or feet and are wearing your own clothing. Some times also spawning in with no hair depending on hair style.

### Expected behaviour

pick the blue team spawn in as blue and be able to see and play like normal.
pick red team get the red team clothing

### Steps to reproduce

fix it lol

### Discord ID

.cumquat

**Comment by fayynt** [comment]
Fixed
