### ISSUE TITLE
[Bug]: Server is lagging

### ISSUE THREAD

**Issue by LGLLewis** [fayynt/issues#25]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

When people are talking they are cutting in and out. Also whilst trying to interact with things such as locks, inventory, pulling guns its very laggy.

ELS is also not working at the moment

### Expected behaviour

For the server to not be laggy and ELS to work

### Steps to reproduce

Try speak to people
Try interact with items
Try using ELS

### Discord ID

695544491679154268

**Comment by fayynt** [comment]
ELS fixed
