### ISSUE TITLE
[Bug]: yacht heist loot unsellable

### ISSUE THREAD

**Issue by xksiitz** [fayynt/issues#26]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

Packed drugs from the yacht heist have no use to sell? Also paintings cannot be sold at the pawn shop 

### Expected behaviour

Paintings to be sellable, explanation how to sell the drugs 

### Steps to reproduce

Idk

### Discord ID

Skitz

**Comment by fayynt** [comment]
Added paintings to pawn shop
