### ISSUE TITLE
[Bug]:  /streamermode no longer works

### ISSUE THREAD

**Issue by AskJeevz** [fayynt/issues#29]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

can no longer use /streamermode to mute music

### Expected behaviour

for it to mute all music in streamer mode

### Steps to reproduce

1. fly in 
2. /streamermode
3. no ears

### Discord ID

Jeevz#0

**Comment by fayynt** [comment]
Potentially fixed please check after restart
