### ISSUE TITLE
[Bug]: Loading screen : PRELOADING COLLISIONS 0%

### ISSUE THREAD

**Issue by BIGJLUK** [fayynt/issues#3]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When connecting to the server, after downloading all the assets, on the loading screen I am faced on PRELOADING COLLISIONS 0% basically just stuck on it, tried clearing cache ect, city issue, more then a few are being faced with this current issue when trying to connect to the city

### Expected behaviour

For me i was fine in city whilst others had this problem, i cleared my cache and then the problem appeared for me.

### Steps to reproduce

N/A 

Happens randomly
![image_2023-08-18_011802447](https://github.com/fayynt/issues/assets/141675103/30f1e32d-b8a7-47ca-b63c-5343322fa604)

### Discord ID

jxxk.lew

**Comment by fayynt** [comment]
Resolved
