### ISSUE TITLE
[Bug]: Police Dog script not working

### ISSUE THREAD

**Issue by OskarHoops** [fayynt/issues#30]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

Police dog script seems to be not working or removed

### Expected behaviour

Settings
pm-k9 spawn dog for eg.
Set keybind
Spawn dog

### Steps to reproduce

Police job
Settings
pm-k9 not there

### Discord ID

1079004704991879229

**Comment by fayynt** [comment]
Removed for the time being
