### ISSUE TITLE
[Bug]: Public LSD bans players taking too much

### ISSUE THREAD

**Issue by RG2Kelvin** [fayynt/issues#34]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

taking public lsd to gain max amour bans players hitting 100 

### Expected behaviour

drug to stop at LDN armour limit 

### Steps to reproduce

spawn lsd and take till banned

### Discord ID

575632373077770260

**Comment by FellaHighOnaBoat** [comment]
@fayynt fixed?

**Comment by fayynt** [comment]
> @fayynt fixed?

Doing 😎

**Comment by fayynt** [comment]
Duplicate of #82 so will close for now
