### ISSUE TITLE
NPAS camera and rappel not working[Bug]: 

### ISSUE THREAD

**Issue by OskarHoops** [fayynt/issues#36]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

NPAS Camera is not an option anymore along with rappel looks like its not even in city anymore

### Expected behaviour

Get in NPAS
Press E 
Camera Opens

Get in rear seat of NPAS 
press X twice 
Rappel down

### Steps to reproduce

Get in NPAS
Press E 
Camera doesnt Open

Get in rear seat of NPAS 
press X twice 
Cannot Rappel down

### Discord ID

1079004704991879229

**Comment by FellaHighOnaBoat** [comment]
Check on restart
