### ISSUE TITLE
[Bug]: INVISIBLE CHARACTERS 

### ISSUE THREAD

**Issue by LordKeefy** [fayynt/issues#39]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

When new players join city they cannot see there character also happening when people delete there cache.

### Expected behaviour

Be able to see character 

### Steps to reproduce

Join city for first time or delete your cache.

### Discord ID

LordKeefy

**Comment by fayynt** [comment]
they need to download assets, dont know what else to say. clearing cache will also cause you to redownload assets. will look into making assets smaller but atm nothing
