### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by evarsm** [fayynt/issues#4]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

players password on phone wont let him open it regardless of not being wrong

### Expected behaviour

n/a

### Steps to reproduce

contact you

### Discord ID

532330634127999002

**Comment by fayynt** [comment]
Can you elaborate? Added a passlock onto the phone and unlocking it works for me.

**Comment by fayynt** [comment]
Cannot replicate. No reply.

**Comment by evarsm** [comment]
not this going to my junks

Sent from Samsung Mobile on O2
Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
