### ISSUE TITLE
[Script]: 

### ISSUE THREAD

**Issue by F1Ellis** [fayynt/issues#41]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

The construction job script doesnt reset after completing all the jobs you have to wait for a restart to see new ones 

### Expected behaviour

Reset all jobs once completed 

### Steps to reproduce

1) clock in as a construction worker
2) complete all the construction jobs 
3) Wait for script to reset and do more jobs 

### Discord ID

722399446620700704

**Comment by fayynt** [comment]
Fixed next restart, will restart every 30 minutes.
