### ISSUE TITLE
[Bug]: WL dealer not working

### ISSUE THREAD

**Issue by LGLLewis** [fayynt/issues#42]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

When i go to buy a WL dealer weapon it does not give me the weapon or take my money
[https://cdn.discordapp.com/attachments/1139696602869669908/1175162783919259729/image.png?ex=656a3aa1&is=6557c5a1&hm=3afc423ac78139a1b3dd1e0064e42438c4556e5a0caf91a598162a96af0a6053&](url)

### Expected behaviour

To be able to buy a WL weapon

### Steps to reproduce

Go to WL Dealer
Third Eye to show weapons
Click on the weapon you want to buy

### Discord ID

695544491679154268

**Comment by FellaHighOnaBoat** [comment]
it works perfectly fine, youre just dumb Lewis
