### ISSUE TITLE
Recycling issue

### ISSUE THREAD

**Issue by BazFletch** [fayynt/issues#45]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

Recycling centre freezes you as you get the product, same bug as the car wash

### Expected behaviour

You would grab the product in your hands and be able to more freely with it to the process point.

### Steps to reproduce

E to pick
Then move freely with product
E when at the process point

### Discord ID

660443509500805130

**Comment by fayynt** [comment]
fixed
