### ISSUE TITLE
[Bug]: Boosting Tablet no workerino

### ISSUE THREAD

**Issue by ChamberlainGoodFayntBad** [fayynt/issues#46]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

Use tablet, tablet no open. Thank you

### Expected behaviour

use tablet=tablet open

### Steps to reproduce

use tablet
tablet open
it no open

### Discord ID

418866408445837329

**Comment by RG2Kelvin** [comment]
Fixed
