### ISSUE TITLE
[Bug]: Elevator for pickle construction

### ISSUE THREAD

**Issue by AskJeevz** [fayynt/issues#47]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

When more than 2 people are on the lift it will phase you through the lift, the other glitch is if you are on your own then go down you can potentially glitch through the bottom of the lift

### Expected behaviour

Not phase through the lift

### Steps to reproduce

Do Construction
get a lift
Profit 

### Discord ID

Jeevz#0

**Comment by fayynt** [comment]
network issue sorry, not fixable atm
