### ISSUE TITLE
[Bug]: Jetski Flying 

### ISSUE THREAD

**Issue by TheOGYonder** [fayynt/issues#49]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

While in a jetski, if you select the cruise control option, The jetski begins to fly instead of going along the water, This Also Works When you use cruise control while heading towards solid land, you then instead of Banking the jetski you fly over the land 

### Expected behaviour

Jetski to stay on water while in cruise control 

### Steps to reproduce

Ride Jetksi
Flex "B"
Hold "W" 

### Discord ID

TheOGYonder#7910

**Comment by RG2Kelvin** [comment]
Was fixed on a recent update, no longer a issue script has been changed
