### ISSUE TITLE
[Bug]: West Coast Customs F9 not working

### ISSUE THREAD

**Issue by LarryDingle** [fayynt/issues#5]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

Anytime i clock in to west coast doesn't allow me to use the F9 menu. Can't use the 3rd eye to check the inside parts of car like the fuel pump or any of that stuff. 

### Expected behaviour

can use the f9 and the 3rd eye

### Steps to reproduce

.

### Discord ID

.cumquat

**Comment by fayynt** [comment]
Cannot replicate after restart. Perhaps it was fixed? Please check for me

**Comment by fayynt** [comment]
Fixed.
