### ISSUE TITLE
[Bug]: Car lock picking not working

### ISSUE THREAD

**Issue by RG2Kelvin** [fayynt/issues#50]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

lockpick dont work if you use hotbar or drag to use 

### Expected behaviour

to be able to lockpick all cars 

### Steps to reproduce

buy lockpick 
goto car 
use lockpick

### Discord ID

575632373077770260

**Comment by fayynt** [comment]
Fixed
