### ISSUE TITLE
[Bug]: Metal Detector

### ISSUE THREAD

**Issue by BazFletch** [fayynt/issues#52]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

When using the metal detector as soon as you use it your game will crash instantly.

### Expected behaviour

Drag to use
Use device to aid the job

### Steps to reproduce

1) Drag to ''Use'' Or press relevant hot-bar Key

### Discord ID

453097675107

**Comment by fayynt** [comment]
Changed model, will test

**Comment by fayynt** [comment]
Removed
