### ISSUE TITLE
[Bug]: Races ending is bugged

### ISSUE THREAD

**Issue by LGLLewis** [fayynt/issues#54]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

When you have say 3 people ina race, once 2 people have finished it will end the full race meaning the 3rd person doesnt get a full race and leaves their kart on the track

### Expected behaviour

For it to allow everyone to finish their race

### Steps to reproduce

Go to Karting
Join a multi race with 3+ people
finish the race

### Discord ID

695544491679154268

**Comment by FellaHighOnaBoat** [comment]
Old V1 bug
