### ISSUE TITLE
[Bug]: PD Evidence Locker Gone

### ISSUE THREAD

**Issue by OskarHoops** [fayynt/issues#56]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

PD Evidence locker no longer where it was

### Expected behaviour

Go to brown shelf
Press E to open evidence prompt

### Steps to reproduce

Go to cells floor armoury next to brown bench evidence locker not there

### Discord ID

1079004704991879229

**Comment by FellaHighOnaBoat** [comment]
New locker was made
