### ISSUE TITLE
[Bug]: [PD] Radar For Reading Plates Is Not Working?

### ISSUE THREAD

**Issue by Cameron2131** [fayynt/issues#57]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

Radar For Reading Plates Is Not Working?

### Expected behaviour

When Trying To Use PD Radar To Read License Plate`s When Turned On It Does Not Read The Plate At All/ Doesnt Even Display The Vehicles Speed Or Vehicle Plate Numbers/Letters

![image](https://github.com/fayynt/issues/assets/149907059/8202f0e4-7d2e-4c94-bd28-e919051d8a52)

### Steps to reproduce

1. Turn Radar On 
2. Set Radar To City Speed Limits.
3. Drive Around But Doesnt Pick Anything Up?

### Discord ID

967383874692874260

**Comment by FellaHighOnaBoat** [comment]
Fixed last night
