### ISSUE TITLE
[Bug]: Invisible PD 90% of the time

### ISSUE THREAD

**Issue by BazFletch** [fayynt/issues#59]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

The interior of the PD is invisible almost 100% of the time as you enter it. This is fixed by driving away and back top it but doesn't really make the city look good.

### Expected behaviour

Walk inside, be able to see 

### Steps to reproduce

Walk inside
Be able to see

### Discord ID

5413907650948104987560

**Comment by FellaHighOnaBoat** [comment]
This is a general fivem streamed asset issue. This can occur with any streamed interior. 

Before any of you PD go _"tHiS nEvEr HaPpEnEd WiTh OuR oLd pD"_
**Yes it did. Just not the middle floor as thats not streamed. That is a default GTA V map**
