### ISSUE TITLE
[Bug]: Bean Machine drinks not working

### ISSUE THREAD

**Issue by DerryOShea** [fayynt/issues#6]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

Doesn't give drinks for the below but takes products

- Ristretto
- Mint Tea

Drinks that don't increase thirst bar

- Green Tea
- Jasmine Tea

Products missing from seller

- Premium Turkish Beans 

### Expected behaviour

Should give end product for Ristretto & Mint Tea
Green Tea & Jasmine Tea should increase thirst bar
Should be able to buy Turkish beans from seller to make Turkish coffee

### Steps to reproduce

Try make the products
Make the products and try and use
Check the seller 

### Discord ID

263434394901938177

**Comment by DerryOShea** [comment]
add - Oreo Muffin to the items that don't increase also doesn't remove from pocket

**Comment by fayynt** [comment]
- Added Premium Turkish Beans to the seller and fixed Jasmine being named as Jasmine Tea.
- Fixed Ristreto and Mint Tea. 
- Potentially fixed Jasmine Tea Green Tea

**Comment by DerryOShea** [comment]
New Issue's
Below are the food/drink that don't do animations some deplete from pockets but none increase on hunger/thirst bar

- Mint Tea
- Jasmine Tea
- Oreo Muffin 
- Vanilla Donut (Does an animation and depletes but give nothing to hunger bar)

Not sure why, sometimes food will stop working until there is restart then it'll work again. checked f8 logs for errors couldn't see any.

**Comment by DerryOShea** [comment]
@fayynt Also the Turkish Tea is the same pal

**Comment by DerryOShea** [comment]
> New Issue's Below are the food/drink that don't do animations some deplete from pockets but none increase on hunger/thirst bar
> 
> * Mint Tea
> * Jasmine Tea
> * Oreo Muffin
> * Vanilla Donut (Does an animation and depletes but give nothing to hunger bar)
> 
> Not sure why, sometimes food will stop working until there is restart then it'll work again. checked f8 logs for errors couldn't see any.

If the items stop working I need to fly out and back in for them to work, not sure if something is conflicting with the script

**Comment by DerryOShea** [comment]
The below is not working again either, sorry to add more to the list
Doesn't give drinks for the below but takes products

- Ristretto

**Comment by DerryOShea** [comment]
![Bean Machine V1 1](https://github.com/fayynt/issues/assets/142450333/72c7e027-09ea-4a7f-901b-fac12e828e5d)
anything with a line through it doesn't work @fayynt
