### ISSUE TITLE
[Bug]: Market Place Tablet Purchasing Bug

### ISSUE THREAD

**Issue by Cameron2131** [fayynt/issues#61]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

When Purchasing Items On The Tablet Which The Price Is Under £6,000 Then You Wont Be Charged For That Item Giving U Free Items And The Other Player/ Seller Would Recieve The Money And From This Makeing Infinite Money If People Was To Do It.

[Market Place Tablet Bug Clip](https://clipchamp.com/watch/sQAlq1IkLMp)

### Expected behaviour

Shouldnt Be Giving Out Free Stuff Should Be Charging U!

### Steps to reproduce

1. Find Item Under Or Is Valued At £6,000
2. Click Purchase
3. Then See No Money Is Being Took From Your Bank

### Discord ID

967383874692874260

**Comment by fayynt** [comment]
removed for the time being.
