### ISSUE TITLE
[Bug]: Yacht Heist

### ISSUE THREAD

**Issue by TheOGYonder** [fayynt/issues#62]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

When doing the yacht heist, Dispatch Doesn't Get Notified that there is a heist in progress 

### Expected behaviour

Dispatch to alert when yacht heist is being done 

### Steps to reproduce

Start Yacht Heist

### Discord ID

TheOGYonder#7910

**Comment by fayynt** [comment]
Yacht heist changed, also fixed
