### ISSUE TITLE
Bus driver job keeps spawning vehicles with low petrol in them so cannot complete the round [Bug]: 

### ISSUE THREAD

**Issue by nath8558** [fayynt/issues#63]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

Bus driver job keeps spawning vehicles with low petrol in them so cannot complete the round

### Expected behaviour

The buses used to spawn with full tanks which was enough for the trips

### Steps to reproduce

1. start the job
2. bus spawns with low petrol
3. cant complete job

### Discord ID

371224522080124930

**Comment by fayynt** [comment]
Fixed
