### ISSUE TITLE
[Bug]: When doing house robbieries the alarm activates straight away instead of having the 4-5 second timer. and majority of cabinets are empty

### ISSUE THREAD

**Issue by nath8558** [fayynt/issues#64]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

When doing house robbieries the alarm activates straight away instead of having the 4-5 second timer. and majority of cabinets are empty

### Expected behaviour

used to have a 5 second timer then alarm went off, and cabinets used to have a lot more stuff.

### Steps to reproduce

1. rob house
2. 2. alarm activates instant
3. first 2 cabinets are all empty

### Discord ID

371224522080124930

**Comment by FellaHighOnaBoat** [comment]
Old V1 bug
