### ISSUE TITLE
[Bug]: whole UI keeps bugging out then dissapears, have to restart game to get it to reappear again

### ISSUE THREAD

**Issue by nath8558** [fayynt/issues#67]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

whole UI keeps bugging out then dissapears, have to restart game to get it to reappear again, cant see cash, hunger, drink, car stuff etc.

### Expected behaviour

UI shouldnt dissapear

### Steps to reproduce

1 play the game
2 Ui bugs
3 UI dissapears
4 retart game to fix it

### Discord ID

371224522080124930

**Comment by FellaHighOnaBoat** [comment]
Issue has been noticed. Fix implimented for restart. Please advise here if this no longer occurs on restart.

Next restart is 30mins away from this comment

**Comment by nath8558** [comment]
UI is still bugging out for me, not as much but still doing it.

**Comment by FellaHighOnaBoat** [comment]
Bug Fix

This update fixes an issue with a third-party library used for OCR image manipulation causing a growing heap buffer until the OOM Killer was triggered causing a nui crash and restart along with fps loss every time it crashed.

Further action has been taken to delay and/or prevent further occurances

**Comment by nath8558** [comment]
does that mean its fixed?
