### ISSUE TITLE
[Bug]:  FleecaHeistt by Rainmad Pay is not substantial/ Back forheistt not sold

### ISSUE THREAD

**Issue by AskJeevz** [fayynt/issues#7]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

The pay for the Fleeca heist when all lock boxes have been looted as well as all gold bars only seems to pay around £5000 for all loot, The bag that is also required is not sold in the black market 

### Expected behaviour

Bag in black market
adjustment on pay

### Steps to reproduce

1. Complete heist
2.go to selling spot
3: profit?

### Discord ID

258320294018678784

**Comment by fayynt** [comment]
Added bag to stab city + increased pay

**Comment by AskJeevz** [comment]
New payout is £500 000
