### ISSUE TITLE
[Bug]: CD Radar Issue not working displays on screen but doesnt function at all

### ISSUE THREAD

**Issue by OskarHoops** [fayynt/issues#70]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

When the radar comes up you should be able to register the speed of cars in front and behing you and lock onto a plate using letter o. However this does not work it only displays the radar

### Expected behaviour

When the radar comes up you should be able to register the speed of cars in front and behing you and lock onto a plate using letter o

### Steps to reproduce

Set job to police get in police vehicle do /radartoggle to get it to appear , test the script

### Discord ID

1079004704991879229

**Comment by FellaHighOnaBoat** [comment]
Old V1 bug
