### ISSUE TITLE
[Bug]: driving test cars do not auto start nor give option to Hotwire

### ISSUE THREAD

**Issue by xksiitz** [fayynt/issues#71]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

The driving test car will not allow people to start engine or Hotwire… this is a pass on issue shown to me by at least 5 people now 

### Expected behaviour

Car to start and or be able to hotwire

### Steps to reproduce

Get in car
Engine start
Fail driving test because terrible driver 

### Discord ID

Skiitz

**Comment by fayynt** [comment]
Fixed, thx for report
