### ISSUE TITLE
[Bug]: Shooting while aiming

### ISSUE THREAD

**Issue by LarryDingle** [fayynt/issues#79]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

Sometimes when you ads with any gun you cannot shoot. It forces you to hip fire.

### Expected behaviour

Be able to ads and shoot my gun

### Steps to reproduce

ads
shoot
win

### Discord ID

.cumquat

**Comment by fayynt** [comment]
is this still happening?
