### ISSUE TITLE
My garage cars dont let me start the engine[Bug]: 

### ISSUE THREAD

**Issue by Soxxxyy** [fayynt/issues#8]
### Is there an existing issue for this?

- [x] I have searched for existing issues

### Description

Whenever I pull out cars from my garage it wont let me start the engines. I press G to start the engine and it does the clicky noise, but no engine start. 

To start the I've been advised by players to do /seat 2 then /seat 1 for my cars only. 

This occurs for dealer cars and my 2x 2'2s. 

### Expected behaviour

For the car engine to start first time. 

### Steps to reproduce

Pull car out of garage and get in. 

### Discord ID

Soxxxyy

**Comment by Soxxxyy** [comment]
Blazed stated that a part may be broken on my cars. Derry looked earlier & so did I as a mechanic and they have 100% everything. I also additionally lose my keys sometimes. Driving around in my cars & get out and then the keys wont let me start the engine again, its like I have no keys.

**Comment by fayynt** [comment]
SInce then, carlock has been removed and then re-added. Most likely fixed.
