### ISSUE TITLE
[Bug]: the bandages that you make from the crafting bench does not work 

### ISSUE THREAD

**Issue by Bigbushburnz2000** [fayynt/issues#80]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

when you make bandages on the crafting bench it does not let you use them 

### Expected behaviour

for the bandages to heal you 

### Steps to reproduce

1 get crafting items 
2 craft bandage
3 use bandage 

### Discord ID

981234603287273502

**Comment by FellaHighOnaBoat** [comment]
Old V1 bug
