### ISSUE TITLE
[Bug]: PD do not get a notification when a boosting is taking place

### ISSUE THREAD

**Issue by AskJeevz** [fayynt/issues#81]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

PD dont get a notification when a boosting job takes place, 

### Expected behaviour

PD get a notification

### Steps to reproduce

1. start boostin
2. no notification
3. sad times

### Discord ID

Jeevz#0

**Comment by FellaHighOnaBoat** [comment]
Old V1 bug
