### ISSUE TITLE
[Bug]:  LSD bans when taking getting too 100 armour

### ISSUE THREAD

**Issue by JagoPrice** [fayynt/issues#82]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

When taking LSD that gets you too 100 armour or higher it bans you

### Expected behaviour

Perm bans you

### Steps to reproduce

Take LSD until you get too 100 armour
Wait a few seconds 
It will ban you

### Discord ID

885249784003321927

**Comment by FellaHighOnaBoat** [comment]
Old V1 bug
