### ISSUE TITLE
[Bug]: NHS Bugs

### ISSUE THREAD

**Issue by xxlondon** [fayynt/issues#83]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

When a doctor goes on shift, '[E] Call Doctor' appears.
1a. In the past this has disappeared after approx. 10 minutes (from when I was doctor on shift alone)
1b. In the past it has flicked on and off with a mind of its own.

ECG
2a. When a person is conscious, the system will not allow you to do CPR on a patient.
2b. You wouldn't use a Defib on a conscious patient due to the risk of death.
2c. The server seems to have a limit you can use ECGs
2d. Once place and you take your eyes away from the ECG, the options are removed, it whereever it is placed, is the ECGs home until Tsunami.

Revive Kits
3a. When a person is conscious and they have injuries, after we've healed them, they do not stand. 
Using a revive kit is the only way to help a person in this state to their feet. - I agree, it isn't perfect, maybe bring in something that will help a person to their feet?

Bodybags
4a. About a week ago, we had unlimited body bags available through the medical system, now it's constantly greyed out.
4B. Sofia mentioned about holding body bags in our inventory, however I or anybody else doesn't know where to find them to put them into the inventory.

### Expected behaviour

Up above

### Steps to reproduce

shown above

### Discord ID

767095793034723348

**Comment by FellaHighOnaBoat** [comment]
@xxlondon 1 bug per report

**Comment by xxlondon** [comment]
np
