### ISSUE TITLE
[Bug]: Car lock picking and skill checking in general has become very slow again

### ISSUE THREAD

**Issue by AskJeevz** [fayynt/issues#84]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

Skill check and lock picking is now really slow, takes alot longer now to lock picks

### Expected behaviour

not take 2 years to lock pick
Thanks

### Steps to reproduce

Find a fed
Mug him off 
try skill check
Profit????

### Discord ID

jeevz#0

**Comment by FellaHighOnaBoat** [comment]
Old V1 bug
