### ISSUE TITLE
[Bug]: Cat Convertor Fail

### ISSUE THREAD

**Issue by jordanw911** [fayynt/issues#85]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

The Angle Grinder didn't cut the catalytic convertor although I got under the car and it gave me the option to cut but when I went to sell it said I didn't have anything to sell

### Expected behaviour

To cut the cat and give it to me so i can sell

### Steps to reproduce

Buy angle grinder. Find random car. cut convertor and go to sell

### Discord ID

vzylozz

**Comment by fayynt** [comment]
Fixed (next restart)
