### ISSUE TITLE
[Bug]: phones

### ISSUE THREAD

**Issue by louieyoyooyoylyo** [fayynt/issues#86]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

i have brought a phone from a shop for 1k and it doesn’t work i bought it and used it but needs a passcode but i didn’t have a option to create one so what should i do

### Expected behaviour

to fix this bug

### Steps to reproduce

i

### Discord ID

ddssssss

**Comment by FellaHighOnaBoat** [comment]
That means you have previously set a passcode

Either remember it or go to the phone repair guy on the map to unlock it.

**THIS IS NOT A BUG**
