### ISSUE TITLE
[Bug]: not being able to shoot when ads

### ISSUE THREAD

**Issue by Kzxio** [fayynt/issues#87]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

Sometimes when pulling a gun out and putting it away it stops you from being able to shoot when ads until you fly out and in.

### Expected behaviour

 fix this issue

### Steps to reproduce

1 fix
2 fix
3 fix

### Discord ID

999128566933487636

**Comment by FellaHighOnaBoat** [comment]
Old V1 bug
