### ISSUE TITLE
[Bug]: jobs

### ISSUE THREAD

**Issue by rustyturtle** [fayynt/issues#88]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

the logging job has a bug where you cant drop the trailer so you have to jackknife and sometimes that causes the trailer to flip
the construction job does not exist on the map 

### Expected behaviour

need a button to drop trailer 
and need to re do the construction job 

### Steps to reproduce

try run both jobs and you will see 

### Discord ID

rustyturtles

**Comment by FellaHighOnaBoat** [comment]
default GTA controls.... but also Old V1 bug
