### ISSUE TITLE
[Bug]: Cartel Heist Invisi

### ISSUE THREAD

**Issue by LGLLewis** [fayynt/issues#89]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

Was on PD and went to the new heist as it was being done, everyone on that island was invisible. After they flew out and back in i could see them again.

### Expected behaviour

For them to not be invis

### Steps to reproduce

Go to the Island
Have someone already on there doing heist

### Discord ID

695544491679154268

**Comment by FellaHighOnaBoat** [comment]
Old V1 bug
