### ISSUE TITLE
Crashing at Bean Coffee Shop[Bug]: 

### ISSUE THREAD

**Issue by Soxxxyy** [fayynt/issues#9]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

Me, Derry & Jake Way were in Bean Coffee shop last night and kept crashing. You would fly back in and instantly crash again. 
This happened about 2/3 times for everyone before it stopped. 

We were clocked in awaiting customers chatting. Not sure if issue is legion proximity or the fence showing through the shop from legion car park. 

### Expected behaviour

Not to crash

### Steps to reproduce

Stand in Bean Coffee shop. I'd spent four hours in that day, and happened towards end of the night around 11:30pm. 

### Discord ID

Soxxxyy

**Comment by fayynt** [comment]
Still happening? If so attach crash dumps
