### ISSUE TITLE
[Bug]: catalytic converters 

### ISSUE THREAD

**Issue by danip123** [fayynt/issues#90]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

when using angle grinders to steal a cars catalytic converter it doesn't give a catalytic converter but takes the angle grinder after you finish the game 

### Expected behaviour

to take a angle grinder and give a catalytic converter 

### Steps to reproduce

get a angle grinder
try it on a car
see results 

### Discord ID

681216574992023561

**Comment by FellaHighOnaBoat** [comment]
Old V1 bug
