### ISSUE TITLE
[Bug]:  NPC NOT SPAWNING FOR WEED KEYCARD  

### ISSUE THREAD

**Issue by BUGGIN123** [fayynt/issues#92]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

after you've purchased the tools and got the location of the NPC who sells you the key card to gain access to the WEED lab.
You get an automatic waypoint on your map but no NPC spawns when you get there. 

### Expected behaviour

Once you arrive at the location set on your map (Always the same location) the NPC should be standing there for you to purchase the key card.  

### Steps to reproduce

1. follow the waypoint set on your map after gaining the information to the whereabouts of the NPC.  
 

### Discord ID

658706577515347973

**Comment by FellaHighOnaBoat** [comment]
Old V1 bug
