### ISSUE TITLE
Cartel heist bug

### ISSUE THREAD

**Issue by Jambo2drip** [fayynt/issues#94]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

when doing the cartel hiest the keycard doesnt always drop. it seems to happen once every ten attempts, even govs cannot help. 

### Expected behaviour

the key card should drop everytime.

### Steps to reproduce

1. keep running cartel hiest to see the keys dont always drop
2. see how often the keys drop 

### Discord ID

1173716760403378202

**Comment by FellaHighOnaBoat** [comment]
Old V1 bug
