### ISSUE TITLE
[Bug]: flecca is bugged

### ISSUE THREAD

**Issue by AskJeevz** [fayynt/issues#95]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

Cant do hacking, can only change every other fingerprint slice
cant hack safe as you cant interact with anything after
when picking up gold will bug and not allow you to interact
cant place thermal charge as will bug

### Expected behaviour

for it to work

### Steps to reproduce

Try Hiest

### Discord ID

Jeevz#0

**Comment by FellaHighOnaBoat** [comment]
Old V1 bug
