### ISSUE TITLE
[Bug]:  Gun stays on your back after putting it away issue.

### ISSUE THREAD

**Issue by ayowhatt** [fayynt/issues#96]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

When I have a gun and put it inside my car, the gun still appears on your back for some people and they rob thinking you actually have a gun on your back but you don't. Once they realize I don't they still take my other items which just means they are robbing me for no reason

### Expected behaviour

The gun should disappear on your back so no one robs you since you literally put it in your glovebox or trunk

### Steps to reproduce

Have a weapon already in your inventory.
Put it in your glovebox or trunk.
And the gun will still stay on your back so players think you have a gun so they rob you.

### Discord ID

opmartinnn

**Comment by FellaHighOnaBoat** [comment]
You can always do /propfix to remove it when this happens

**Comment by ryanizgod** [comment]
> You can always do /propfix to remove it when this happens

It don’t work people can still see pistol , msg and AR on your back or side , it goes for yourself but not others.

**Comment by FellaHighOnaBoat** [comment]
Old V1 bug
