### ISSUE TITLE
[Bug]: safe at fleece stop being able to continue the heist 

### ISSUE THREAD

**Issue by JagoPrice** [fayynt/issues#98]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

When cracking the safe at fleece bank to get the keycard to get into the vault room it makes it so you don’t crack the code, also it stops you from accessing any other parts of the heist as well.

### Expected behaviour

Stops you from being able to interact with stuff in fleece, meaning that you can’t access the vault and take the stuff that you would normally get.

### Steps to reproduce

1: Start fleece by shooting inside
2: get through the first door of the bank
3: try and lock pick the safe on the right side of the door before reaching the vault door.
4: you’ll see that you cannot access anything else and you can’t carry on the bank

### Discord ID

885249784003321927

**Comment by FellaHighOnaBoat** [comment]
Old V1 bug
