### ISSUE TITLE
[Bug]: can’t use drill

### ISSUE THREAD

**Issue by ryanizgod** [fayynt/issues#99]
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

When doing bank heist , you get in the vault and go to drill the safe boxes and it says you need a drill when you have 5 on you , also couldn’t pick up the gold? But at the end your drills are gone?

### Expected behaviour

Drill the safe boxes to get content inside.

### Steps to reproduce

1. Get in safe 
2. Drill safe boxes 
3. Says need drills to do this
4. Won’t open safe boxes 
5. Have to fail that bit of heist but at end when away shows drills are gone

### Discord ID

448201668543381534

**Comment by FellaHighOnaBoat** [comment]
Old V1 bug
